### ISSUE TITLE
Could the proteus build without Clion?

### ISSUE THREAD

**Issue by Yongze-zzz** [epfl-dias/proteus#1]
I am curious about proteus, it seems like a htap database. I try to build it with command "sudo docker run -it --gpus all -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) --mount type=bind,source=/home/yanyz/db/proteus,target=/home/yanyz/db/proteus --security-opt seccomp=/home/yanyz/db/proteus/tools/docker/proteus-build/seccomp.json --cap-add=SYS_NICE --cap-add=IPC_LOCK proteusdb/proteus-dev:cuda11.3-llvm14.0.0 /bin/bash" . Then I run "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/yanyz/db/proteus/opt". But cmake process is failed. I wanna know could i build proteus without clion?

**Comment by Shamazo** [comment]
Hi, could you provide the error that caused CMake to fail? Clion is not a dependency, it is just the preferred development setup.

**Comment by Yongze-zzz** [comment]
Hi Shamazo, thanks for your reply. Now cmake is work, but there are some make errors : 
![image](https://github.com/epfl-dias/proteus/assets/70116723/86ea8f3b-e861-4012-9d2d-314d5ae4a6e2)
Should I change the CUDA sm value . I use cuda11.3,and NVIDIA RTX A5000

**Comment by Shamazo** [comment]
From this information, it is unclear what the precise problem is. It seems to be an issue with your Clang or Cuda. Your RTX A5000 has a compute capability of 8.6 (sm_86). Cuda 11.3 should support your RTX A5000. The version of Clang/LLVM in our [toolchain](https://github.com/epfl-dias/pelago) should probably support Cuda 11.3.

**Comment by Yongze-zzz** [comment]
Hi Shamazo, I have built proteus successfully. Could you provides some details about how to run ch-benchmarks and tpc-c? It would help me to better understand the proteus. Thank you very much.
